name: CultureOS Automated Deployment

on:
  push:
    branches:
      - main # Trigger workflow on every push/merge to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Local Dependencies
        run: npm ci

      - name: Run Deploy Script
        env:
          ECS_HOST: ${{ secrets.ECS_HOST }}
          ECS_USERNAME: ${{ secrets.ECS_USERNAME }}
          ECS_PASSWORD: ${{ secrets.ECS_PASSWORD }}
          ECS_REMOTE_PATH: '/opt/culture-os'
        run: node deploy.js
